# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Check generated files

on:
  push:
    paths:
      - '.github/workflows/check-generated-files.yml'
      - 'tooling/api/src/**'
      - 'core/tauri/scripts/bundle.global.js'
      - 'core/tauri-utils/src/config.rs'
      - 'tooling/cli/schema.json'
      - 'core/config-schema/schema.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      bundle: ${{ steps.filter.outputs.bundle }}
      schema: ${{ steps.filter.outputs.schema }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            bundle:
              - 'tooling/api/src/**'
              - 'core/tauri/scripts/bundle.global.js'
            schema:
              - 'core/tauri-utils/src/config.rs'
              - 'tooling/cli/schema.json'
              - 'core/config-schema/schema.json'

  check-bundle:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.bundle == 'true'
    steps:
      - uses: actions/checkout@v2

      - name: generate bundle
        working-directory: tooling/api
        run: yarn && yarn build
      - name: check bundle
        run: ./.scripts/ci/has-diff.sh

  check-schema:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.schema == 'true'
    steps:
      - uses: actions/checkout@v2

      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: core -> ../target

      - name: generate schema.json
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./core/config-schema/Cargo.toml

      - name: check schema
        run: ./.scripts/ci/has-diff.sh
